### ISSUE TITLE
Name resolution with external service not working

### ISSUE THREAD

**Issue by graywh** [ysbaddaden/prax.cr#102]
Using `appname.ip.address.nip.io`, prax only wants to serve the app linked to `~/.prax/default`.  I'm running 8.1-1 on Ubuntu 18.04.5.  `appname.test` works fine.

**Comment by ysbaddaden** [comment]
Prax doesnt know about nip.io. It only knows and supports xip.io.

This should be easy to add if you want to take a stab at it.

**Comment by graywh** [comment]
#103
