### ISSUE TITLE
timeout starting application

### ISSUE THREAD

**Issue by jcarlos7121** [ysbaddaden/prax.cr#21]
Hi!!! i wanted to ask something, i configured and linked my app folder to prax, and when i access it on the URL myapp.dev, prax starts the rackup, but, my app has a very specific configuraction that it makes compilation of assets and it always delays many seconds on the first shot, and as consequence prax sends me a timeout starting application, is there a way i can increase the wait time? my app has a very specific config, cause its trying to compile a second project that is for the frontend. Or, is there a way i can get in charge of making the rackup in a specific port for prax to make the redirection?, for example if i would like to make a foreman start for starting the app.

Thank you!

**Comment by jcarlos7121** [comment]
nerver mind, i created a file named as the domain i want and the port i want it to be forwarded, also i  had to configure dnsmasq for the .dev domain to be recognized by google chrome.

Thanks anyway!

**Comment by ysbaddaden** [comment]
Maybe the startup maximum waiting time should be configurable with a global environment variable,like `PRAX_TIMEOUT=seconds`.

How did you install Prax? The deb package should have configured the NetworkManager's dnsmasq already.
