### ISSUE TITLE
Are TLDs other than .dev possible?

### ISSUE THREAD

**Issue by elorest** [ysbaddaden/prax.cr#24]
I'd like to use this on a remote vim dev VPS. Currently I just browse to my domain.com:3000. Being able to do something like app.mydomain.com would be amazing.

**Comment by ysbaddaden** [comment]
This is untested, but Prax should accept any TLD you feed it. So, all you need is have Prax running on the server and either:

- have a subdomain wildcard on your VPS DNS configuration for subdomains;
- have a local DNS resolver (eg: dnsmasq) configuration that would resolve `.dev` or any other special TLD to your server IPs, so you can use Prax with whatever domain under that TLD.

That being said:

- if all you need are subdomains, then a DNS wildcard + iptables port redirection shall be enough.
- Prax is a local development tool that is supposed to run within a secured local network, so it takes security *very* lightly. Please keep this in mind!

**Comment by isaacsloan** [comment]
Thanks. I already use iptables to block port 80 to everywhere but my current ip. I just wanted to be able to browse to nice subdomains without setting it up in nginx and having to refresh every time I load. Glad the crystal rewrite is going nicely. I've been loving crystal for the last couple months.
