### ISSUE TITLE
How to run in production mode?

### ISSUE THREAD

**Issue by musaffa** [ysbaddaden/prax.cr#28]
I tried to run by setting RACK_ENV="production" in `.env` but I get the following error:

```
bundler: failed to load command: rackup (/home/musaffa/.rbenv/versions/2.3.1/bin/rackup)
ActiveRecord::AdapterNotSpecified: '"production"' database is not configured. Available: ["default", "development", "test", "load_test", "production"]
```

But my production database is already specified and it works well with: 

```
RACK_ENV=production bundle exec rackup -p 3000
```

**Comment by ysbaddaden** [comment]
it can't find the `"production"` environment, including the quotes. This is a problem in the `.env` parser that won't remove the quotes. As a workaround you may omit the quotes:

```sh
RACK_ENV=production
```

**Comment by musaffa** [comment]
Oh thanks. :+1:

**Comment by ysbaddaden** [comment]
Closing, since we don't parse `.env` files anymore. Use the `.praxrc` shell script instead.
