### ISSUE TITLE
Thread Pool vs Evented IO

### ISSUE THREAD

**Issue by ysbaddaden** [ysbaddaden/prax.cr#3]
Instead of firing a pthread on each request, Prax should have a pool of thread, or rely on an event loop.

**Comment by ysbaddaden** [comment]
This is tied to what Crystal comes up with. The threaded version was quick to develop.

Attemtps to use the libuv based IO model of Crystal didn't go that well for now —it requires to drop the `IO.select` loops, to find a way around File#reopen (libuv doesn't wrap dup, dup2 or dup3), and certainly more.

This is a long term ticket, to keep up with whatever concurrency/parallelism scheme Crystal thrives for.

**Comment by ysbaddaden** [comment]
Note that since #8 Prax uses a thread pool (fixed to 16) instead of spawning a thread to handle each connection.

**Comment by ysbaddaden** [comment]
Crystal 0.7.0 initiated the move to evented IO by default, and Prax now takes advantage of it since 261f119ff85ada7cbdb2b56c62f27a144b6de7bc.

**Comment by asterite** [comment]
That's the spirit!! :-) :-) :-)

**Comment by ysbaddaden** [comment]
A part of me would like to keep control over what runs in parallel, but another part just want Erlang actors and not bother with concurrent vs parallel. I wish crystal will allow just that.
