### ISSUE TITLE
Improve compatibility with dotenv

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ysbaddaden/prax.cr#36]
In my application, I'm using the dotenv gem to load a ".env" file with the following contents:

```
PROTOCOL=http:
BASE_DOMAIN=example.dev
AUTH_APP_URL=$PROTOCOL//$BASE_DOMAIN
```

dotenv supports bash-style variable substitution, so if dotenv were the first code to parse my ".env" file, then `ENV["AUTH_APP_URL"]` would be `http://example.dev`.

However, because I'm using Prax to start my application, and Prax also parses ".env" files and sets the environment variable `AUTH_APP_URL`, but Prax doesn't seem to support variable substitution, and because dotenv internally sets `ENV` with the Ruby code `ENV[k] ||= v` (I think because users wanted to override ".env" variables via CLI), I believe that for all these reasons `ENV["AUTH_APP_URL"]` ends up being `$PROTOCOL//$BASE_DOMAIN`, which seems to be breaking the code in my application that uses `ENV["AUTH_APP_URL"]`.

Therefore, I'd like to discuss a strategy for improving compatibility with the dotenv gem.

A quick peek at Pow reveals to me that they use ".powrc" and ".powenv", but not ".env". I see that Prax already supports ".praxrc" so as "to configure variables", so is ".env" necessary? To improve parity with Pow, and to avoid racing with dotenv, I'd like to (selfishly) suggest that support for ".env" loading be removed from Prax. I imagine there may be some users who rely on this feature, so maybe to smooth migration, ".env" could be deprecated at first, with a message encouraging users to use ".praxrc" instead.

In combination with deprecation, or simply as a new feature to improve dotenv compatibility, or for backwards compatibility, maybe it could also be possible to configure whether or not Prax loads ".env" files.

**Comment by ysbaddaden** [comment]
It sounds legit to drop `.env` now that we have `.praxrc`. I still like `.env` better, because it's more generic across tools, but different tools allow different parsing... sigh. Maybe we could interpolate variables as they are read from `.env`, looking in just parsed variables, then falling back to `ENV`?

**Comment by jacksonrayhamilton** [comment]
Regarding interpolation: You could support it if you want. It wouldn't matter much to me, as long as Prax at least supported simple interpolation like `VAR=$OTHER_VAR`.

Although, for full compatibility with dotenv, Prax would also want to support other shell-isms, including optional `export`, optional single or double quotes, optional `{}` (like `${VARIABLE}`), and escaping the `$` with `\` (like `STATEMENT=SHOW ME THE \$\$\$`). (See [`dotenv/parser.rb`](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/parser.rb) and [`dotenv/variable.rb`](https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/substitutions/variable.rb).)

Personally, I wouldn't do it, as it seems to beckon maintaining a miniature embedded shell language.

**Comment by ysbaddaden** [comment]
Sigh, `.env` should be a simple `A=B` mecanism for providing the app with some per-install values, and then let the app interpolate the values, if necessary, from those bits...

**Comment by jacksonrayhamilton** [comment]
Yep, this situation stinks. Another solution might be to keep the current ".env" parsing behavior, but allow the name of the file to be configured, so it could still be utilized, but not conflict with dotenv.

**Comment by jacksonrayhamilton** [comment]
Another idea for implementing this: We rip the bandage off.  We can immediately drop support for ".env", but if a ".env" file is detected in a project, Prax will print "Setting environment variables via '.env' has been removed.  Please use a '.praxrc' shell script in the project to set environment variables instead.  Disable this message by setting `PRAX_ACKNOWLEDGE_ENV_REMOVAL=true`."

I figure this may be better than deprecation and eventual removal, since we can immediately save dotenv users from the same fate that I had, also the removal is going to inconvenience people at some point no matter what (some people will wait to deal with deprecation until the bitter end).

**Comment by jacksonrayhamilton** [comment]
Sweet, we finally fixed it! :handshake: Can we make a release?

**Comment by ysbaddaden** [comment]
Yes: v0.7.0

**Comment by jacksonrayhamilton** [comment]
Installed the .deb yesterday and it worked just dandy.
