### ISSUE TITLE
application overview

### ISSUE THREAD

**Issue by alexanderadam** [ysbaddaden/prax.cr#38]
It would be nice to have an application overview under [http://prax.dev/](http://prax.dev/).
Basically a link list:
- myapp1
- myapp2 (alias1, alias2)

**Comment by tijn** [comment]
@alexanderadam I made something for that https://github.com/tijn/index.dev

**Comment by ysbaddaden** [comment]
@tijn this is very nice! I like that it's just an app, and can be compatible with different solutions.

**Comment by alexanderadam** [comment]
👍
