### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by kwstannard** [ysbaddaden/prax.cr#46]
distro: Debian Jessie
installed via latest .deb package
```sh
>> prax start -v
Prax 0.6.1-1 (2016-10-13)
>> ls -la /home/kwstannard/.prax/
total 8
drwxr-xr-x  2 kwstannard kwstannard 4096 Feb  9 10:37 .
drwxr-xr-x 66 kwstannard kwstannard 4096 Feb  9 10:22 ..
lrwxrwxrwx  1 kwstannard kwstannard   28 Feb  9 10:22 casper -> /home/kwstannard/work/Casper
>> cat /home/kwstannard/.prax/casper/config.ru 
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)

run Rails.application
>> prax start -V
I, [2017-02-09 10:40:09 -0500 #32262]  INFO -- prax: binding to [::]:20559

# in another tab
>> curl http://casper.dev
curl: (7) Failed to connect to casper.dev port 80: Connection refused
```
Doesn't work in browser either and returns an immediate server not found. `rails s` works perfectly.

**Comment by kwstannard** [comment]
might be related to this? https://github.com/ysbaddaden/prax.cr/commit/e0f44adbe21284b417ecdba66dcb63fca3daafc5

There is nothing about prax in my nsswitch.conf

**Comment by ysbaddaden** [comment]
No. Prax doesn't use the NSSwitch extension anymore.

I never used the deb package on Debian, only on Ubuntu, where it configures the dnsmasq used by NetworkManager to resolve `.dev` to localhost. Maybe Debian uses something different?

**Comment by kwstannard** [comment]
Thanks for the quick reply. You are right, I deleted the change I made to nsswitch.conf, restarted network manager, and now it works. Perhaps we can restart network-manager in postinstall or have it in the install instructions?

**Comment by kwstannard** [comment]
While you are here, do you know how to increase the timeout length? This app takes like a minute to go from boot to rendering a page.

**Comment by kwstannard** [comment]
Figured out what is causing timeout, will open a new issue.

**Comment by ysbaddaden** [comment]
There was #21 about this, but it never got implemented I guess.
