### ISSUE TITLE
Timeout is too short

### ISSUE THREAD

**Issue by kwstannard** [ysbaddaden/prax.cr#47]
https://github.com/ysbaddaden/prax.cr/blob/0accf01f6dcd6ad4b0b067adb0f50f97745963ca/src/prax/application/spawner.cr#L138

This basically makes prax useless for anyone with a legacy rails app.

1) Why is there a timeout? Could it just be deleted?
2) If not deleted, maybe we could add a flag/env var to alter the timeout?

**Comment by ysbaddaden** [comment]
1. no, maybe there is another issue (e.g. the HTTP server failed, but the app won't exit);
2. yes, there should be a `timeout` configuration.

**Comment by kwstannard** [comment]
I have a commit, let me open a PR.
