### ISSUE TITLE
deb package should add depends for dnsmasq

### ISSUE THREAD

**Issue by halida** [ysbaddaden/prax.cr#53]
Like this:

```
DEB_DEPENDENCIES = "-d 'libssl1.0.0' -d 'dnsmasq > 0'"
```
So install deb package will let user know he should install dnsmasq.

**Comment by ysbaddaden** [comment]
No. I don't know about Debian, but Ubuntu already uses dnsmasq with NetworkManager (actually `dnsmasq-base`) for which the deb package merely installs a config file. Adding the `dnsmasq` package would introduce an unwanted dependency.

**Comment by ysbaddaden** [comment]
Maybe add a `Recommend`.
