### ISSUE TITLE
Probably isn't the right place but I'm having issues setting up Prax

### ISSUE THREAD

**Issue by mcr431** [ysbaddaden/prax.cr#57]
My application IP is resolving to 127.0.53.53 instead of 127.0.0.1. I don't really have any clue where to go with this. I did the couple things listed in the Troubleshooting section but don't know what to do to fix it.

Any help would be greatly appreciated. Below is console output:

```xxx@xxx:~/RubymineProjects/CarbonAPI$ getent hosts carbonAPI.dev
127.0.53.53     carbonAPI.dev

xxx@xxx:~/RubymineProjects/CarbonAPI$ sudo /etc/init.d/prax status
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
2    REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
2    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp      ::/0                 ::1                  tcp dpt:80 redir ports 20559
2    REDIRECT   tcp      ::/0                 ::1                  tcp dpt:443 redir ports 20558
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:80 redir ports 20559
2    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:443 redir ports 20558
3    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:80 redir ports 20559
4    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:443 redir ports 20558```

**Comment by tadiou** [comment]
I'm having the same issue here.

`127.0.53.53` gives you the `ERR_ICANN_NAME_COLLISION` error... which'll prevent anything from peeking through. Reason is? `.dev` apparently. I saw some things re: Vagrant that had similar issues. I don't know exactly how to resolve them or anything.

@mcr431 have you had any luck yet?

**Comment by ysbaddaden** [comment]
I'm afraid I can't really help much here. This appears to be related to the DNS resolver. `dnsmasq` should resolve `.dev` domains as `127.0.0.1` or `::1` but doesn't.

**Comment by zachary-huang** [comment]
I had the same issue before.  The resolving issue go away after I modified this file. `/etc/nsswitch.conf` .  I basically add the prax before the dns 
`/etc/nsswitch.conf`

**Comment by coder2000** [comment]
.dev is a TLD and administered by Google according to [this](https://iyware.com/dont-use-dev-for-development/) article. I recommend changing it to .local or .test

**Comment by ysbaddaden** [comment]
The default TLD has been changed from `.dev` to `.test`. `.localhost` is also supported. Actually, any TLD can be used, as long as the computer is configured to resolve `*.tld` as `127.0.0.1` and/or `::1`.
