### ISSUE TITLE
I see  prax-help: not found

### ISSUE THREAD

**Issue by zachary-huang** [ysbaddaden/prax.cr#58]
I am seeing `/usr/bin/prax: line 17: exec: prax-help: not found` after rebooted the machine.  My os is debian 8.8 jessie

**Comment by ysbaddaden** [comment]
Hello, did you find the root issue?

**Comment by zachary-huang** [comment]
I uninstalled and installed it many times but unfortunately, it doesn't resolve the issue.  I went to the final solution "delete my vagrant box and create another one'.  I  guess it may be my system issue, so I close the ticket.
