### ISSUE TITLE
Error starting application

### ISSUE THREAD

**Issue by swcraftsmen** [ysbaddaden/prax.cr#60]
I am seeing the following message.  The message is exactly messaged when I run `bundle exec rails s`.  Normally, it means the server start successfully but I am still getting 500 internal error.   I don't see any other message.

```
2017-07-07T18:44:33.514Z 3183 TID-grgyrcjko INFO: SidekiqScheduler is disabled
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.3-p222), codename: Owl Bowl Brawl
* Min threads: 1, max threads: 1
* Environment: development
* Listening on tcp://localhost:41987
Use Ctrl-C to stop
```

**Comment by ysbaddaden** [comment]
What happens exactly with Prax?

**Comment by ysbaddaden** [comment]
Closing. Missing input from issue author.
