### ISSUE TITLE
switch to another tld

### ISSUE THREAD

**Issue by alexanderadam** [ysbaddaden/prax.cr#61]
It seems that [`.dev` is an official gTLD](https://icannwiki.org/.dev) and [Chrome will soon force https](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/) if I understood this correctly.

So it might be be to switch to another tld (alone to avoid conflicts).

**EDIT:** [here is another good article](https://iyware.com/dont-use-dev-for-development/) that explains the topic a bit better and recommends `.localhost`, `.invalid` and `.test` and `.example` more or less for different purposes. But I guess in the end it doesn't matter and depends on personal taste.

**Comment by ysbaddaden** [comment]
Yeah, I guess :(

Anyway, Prax handles other TLDs transparently. You may use `.localhost` or configure dnsmasq to resolve `*.test` as `127.0.0.1`. We should change the default `.dev` to either one, thought.

**Comment by jacksonrayhamilton** [comment]
A bug has been filed for the ".test"/".localhost" URL bar searching behavior: https://bugs.chromium.org/p/chromium/issues/detail?id=794001
