### ISSUE TITLE
Starting an application using Thin results in a timeout.

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ysbaddaden/prax.cr#62]
When I try to start up an application using the WEBrick web server, Prax can start it successfully.  But if I try to use [Thin](https://github.com/macournoyer/thin), I get the following error:

```
E, [2017-09-26 16:39:58 -0700 #994] ERROR -- prax: timeout starting application: example
```

I believe that it's possible to open a TCP connection to WEBrick ([as prax does](https://github.com/ysbaddaden/prax.cr/blob/0accf01f6dcd6ad4b0b067adb0f50f97745963ca/src/prax/application.cr#L66)), since when I rackup in one terminal:

```
bundle exec rackup --host localhost --port 1234
```

And then in another terminal, do:

```
nc localhost 1234
```

Then netcat hangs.  But if I try to connect in the same way to a Thin server, I immediately get this output:

```
localhost [127.0.0.1] 1234 (?) : Connection refused
```

Maybe Prax needs a better / alternative heuristic for detecting that the server has started?

It is possible for me to connect to my Thin server with:

```
curl -i -X HEAD http://localhost:1234
```

Maybe firing a HEAD would be more reliable?

**Comment by ysbaddaden** [comment]
I'm confused. If I can't make a TCP connection, how am I supposed to send a HTTP HEAD?

**Comment by jacksonrayhamilton** [comment]
I'm not sure.  I am able to make a connection to a Thin server with `curl -i -X HEAD http://localhost:1234`.  It seems like Thin wants us to actually send some data to it.

**Comment by jacksonrayhamilton** [comment]
Well, seems like Prax is able to connect to Thin if we make this change:

```diff
diff --git a/src/prax/application.cr b/src/prax/application.cr
index bb8ef2d..5beacbb 100644
--- a/src/prax/application.cr
+++ b/src/prax/application.cr
@@ -63,7 +63,7 @@ module Prax
     end
 
     def connect
-      socket = TCPSocket.new("127.0.0.1", port)
+      socket = TCPSocket.new("::", port)
       yield socket
     ensure
       socket.try(&.close)
```

**Comment by jacksonrayhamilton** [comment]
Unfortunately, while my above fix works for a Thin web server, it seems to break the following functionality:

- Place a file named "foo" with the contents "1234" into `~/.prax/`
- Go to some directory and use the Node.js package "http-server" to start a server on port 1234 (run this command: `http-server -p 1234 --cors`)
- Visit http://foo.dev

Previously I was able to see files served here.  Now, I get:

```
Proxy Error

Couldn't proxy request to foo.dev:1234.

Error connecting to ':::1234': Connection refused
```

**Comment by ysbaddaden** [comment]
Because `::` means using IPv6 to connect, and http-server probably only binds an IPv4 address.

**Comment by jacksonrayhamilton** [comment]
Any suggestions on other things to try?  I think you might have a stronger background in networking and this project than I.  Otherwise, I could implement checking-for-a-running-server-via-HEAD-request.

**Comment by ysbaddaden** [comment]
We can't send a HEAD request if we can't connect a `TCPSocket`. That's all Prax is trying to achieve: to connect to the socket, it's not trying to send anything that could block or hang Once it *could* connect, then we assume the HTTP server has been started, and we can start to send data. I.e. proxy HTTP requests over the *connected* TCP socket.

For some reason when you use Thin, Prax can't connect to `127.0.0.1` on the expected port. In my knowledge, this is the most conservative IP address we can try to connect to, and which thin should bind to... but alas, it seems it *doesn't*.

Maybe this is related to `thin` itself, maybe to how `lo` is configured, or maybe how `localhost` (which Thin may be using to bind its server to)?

**Comment by jacksonrayhamilton** [comment]
Alright, it sounds like any Rack server ought to be connectible in this way, so I think we ought to bring the issue to Thin, instead.

Although, I am thinking I won't need to be using Thin for the time being, so I won't be pursuing a resolution right now.
