### ISSUE TITLE
Can installation be made easier on Debian 9?

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ysbaddaden/prax.cr#65]
On Debian 9, if I try to install the latest release, I get an error:

```
$ wget https://github.com/ysbaddaden/prax.cr/releases/download/v0.7.0/prax_0.7.0-1_amd64.deb
$ sudo gdebi prax_0.7.0-1_amd64.deb
[sudo] password for jackson: 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libssl1.0.0
```

There doesn't seem to be a libssl1.0.0 on Debian 9, only libssl1.0.2, according to [this answer](https://unix.stackexchange.com/a/394462/64423).

I was able to work around this by installing the Debian 8 version from [here](https://packages.debian.org/jessie/amd64/libssl1.0.0/download):

```
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
sudo gdebi libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
sudo apt-mark auto libssl1.0.0
```

It'd be nice if it was possible to install the package on Debian 9 without needing to resort to old packages.  Do you have any ideas on how to do that?  Perhaps upgrade to the latest libssl, or support both versions somehow?

**Comment by ysbaddaden** [comment]
Prax should be compiled for Debian 9.

Furthermore, I don't support sysyemd (I still run Ubuntu Trusty) so you'll probably have other issues with port redirections and initd start scripts, too.

**Comment by jacksonrayhamilton** [comment]
> Prax should be compiled for Debian 9.

Can you clarify?  Are you saying I should compile it to solve this?  Or that another ".deb" should be provided in the releases page for Debian 9?  (I'm fine with either; but if Debian isn't going to be fully supported, then maybe that should be clarified on the releases page, if I didn't miss that it already is.)

I haven't had many issues with the package so far.  But thanks for the heads up.  And if those things become an issue I may contribute fixes for them.

**Comment by ysbaddaden** [comment]
Having a differently named libssl package means that the OpenSSL version may probably has ABI incompatibilities, so yeah, Prax should probably be compiled for Debian 9 specifically.

I'm not sure I'll be able to maintain specific packages by myself, thought.

**Comment by jacksonrayhamilton** [comment]
I think Crystal supports multiple versions of OpenSSL, including 1.1, which is available on Debian 9, so allowing multiple versions in the ".deb" might just work.
