### ISSUE TITLE
Please create next release.

### ISSUE THREAD

**Issue by jacksonrayhamilton** [ysbaddaden/prax.cr#73]
With “.test” and Debian 9 support added, I would appreciate if an official release were made available so I could simplify my setup scripts.  Thanks!

**Comment by jacksonrayhamilton** [comment]
@ysbaddaden May we have another release, please?

**Comment by ysbaddaden** [comment]
Done: v0.8.0.

**Comment by jacksonrayhamilton** [comment]
Great, thank you!
