### ISSUE TITLE
$RBENV_VERSION

### ISSUE THREAD

**Issue by graywh** [ysbaddaden/prax.cr#79]
I use Rbenv and ran into an issue with Prax using the wrong Ruby version for applications because of the $RBENV_VERSION environment variable in the shell where I started Prax.

Should Prax remove/unset that variable before starting up an application?

**Comment by ysbaddaden** [comment]
Prax doesn't deal with version manager specifics. Maybe you can invoke Prax through a wrapper shell script that will unset some environment variable?

```sh
#! /usr/bin/env sh
unset RUBY_VERSION
exec /opt/prax/bin/prax $*
```

**Comment by graywh** [comment]
Could you at least add this to the Rbenv section of the wiki page?

**Comment by ysbaddaden** [comment]
Also, have you seen https://github.com/ysbaddaden/prax.cr/wiki/Ruby-Version-Managers ? You may just add `unset RUBY_VERSION` in `~/.praxconfig` (maybe).

**Comment by graywh** [comment]
unset in .praxconfig seems to work

thanks

**Comment by ysbaddaden** [comment]
Great! I updated the wiki page with this.
