### ISSUE TITLE
prax-binary: error while loading shared libraries: libevent-2.0.so.5

### ISSUE THREAD

**Issue by scope2229** [ysbaddaden/prax.cr#87]
After installing Prax.cr im getting this error 

/opt/prax/bin/prax-binary: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory

I thought it might be something simple to solve with

$ sudo apt install libevent-dev

This failed though and after removing prax and reinstalling its failing again.

anyone experienced this before

XUbuntu 18.04

**Comment by ysbaddaden** [comment]
The package was built on Ubuntu 14.04 and is incompatible with newer Ubuntu versions. Please build Prax from source.

**Comment by scope2229** [comment]
Thanks compiling fixed this.

**Comment by botandrose** [comment]
Ran into this today. 14.04 is EOL. Any plants to support 16.04, 18.04, and/or 20.04?

**Comment by scope2229** [comment]
it works fine in 16.04 and 18.04. You need to build from source though. The wiki is pretty detailed on how to install from source. For 20 I haven't looked so i couldnt say but i cant see why it wouldnt work. 

Just remember you need crystal installed before you can compile.

**Comment by botandrose** [comment]
Thanks for the quick response! And my apologies, my question wasn't very clear. I meant to ask if there were any plans to release .debs for currently-supported Ubuntu LTS versions.

**Comment by scope2229** [comment]
This I can't answer sorry but im sure if we pulled together to create one, Yasbaddaden could then upload to the necessary locations.

**Comment by scope2229** [comment]
@botandrose It does look like the makefile is able to create a deb package for you to then install that way. but i've not tested it yet.
