### ISSUE TITLE
https fails with no errors

### ISSUE THREAD

**Issue by scope2229** [ysbaddaden/prax.cr#88]
going to https://mysite.dev/ fails to connect 

$ PRAX_DEBUG=1 prax start

RVM loading: ~/.rvm/environments/ruby-2.6.4@mysite
RVM loading: ~/.rvm/environments/ruby-2.6.4@mysite
I, [2019-09-21 20:10:55 +08:00 #8247]  INFO -- prax: binding to [::]:20559
I, [2019-09-21 20:11:00 +08:00 #8247]  INFO -- prax: starting rack application: mysite (port 38311)

i've tried using $ prax certificates but that also fails to create a cert with a few errors. 
With ruby prax i created the certs by hand without ssl3 and there wasnt a problem

**Comment by ysbaddaden** [comment]
`.dev` is now an official TLD by google and often fails to resolve. Use either `.test` or `.localhost` instead.

**Comment by scope2229** [comment]
That was the first thing i tried. Still no errors 
I've setup dnsmasq correctly also but both .test and .dev fail to load in https 
.dev loads with http  .test does not ???

**Comment by scope2229** [comment]
Ah i think i may have solved both when adding test to dnsmasq i added the same configs for dev these were conflicting with each other a simple edit and restart of dnsmasq has solved the issue. 

On a chatty note dam i hate google ive been using .dev for so long why suddenly say oh we own it gggrrrr %$#%@$#%$@%#

Thanks for your input ysbaddaden. Your work is highly appreciated.

**Comment by ysbaddaden** [comment]
I settled on `.localhost` myself. It usually just works on recent distributions (either `systemd-resolved` or `dnscrypt-proxy`, maybe both) so I don't need `dnsmasq` anymore.
