### ISSUE TITLE
OpenSSL Errors

### ISSUE THREAD

**Issue by scope2229** [ysbaddaden/prax.cr#89]
Inside prax-certificate you should remove some of the fields as they shouldnt be blank and you cant create the certs with them 

openssl req -new -key "$ssl_path/server.key" -out "$ssl_path/server.csr" -subj "/C=/ST=/L=/O=Prax Dev Cert/OU=/CN=localhost"

openssl req -new -key "$ssl_path/server.key" -out "$ssl_path/server.csr" -subj "/O=Prax Dev Cert/CN=localhost"

**Comment by ysbaddaden** [comment]
Please open a PR.
