### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by scope2229** [ysbaddaden/prax.cr#92]
I installed previously and it worked fine. i've just reinstalled a new OS and tried again to install however now I' getting this error and im not very good with crystal 

In src/prax/application.cr:94:17

 94 | channel = Channel::Unbuffered(String).new
                ^------------------
Error: undefined constant Channel::Unbuffered

**Comment by scope2229** [comment]
Must use any version between 0.20.1 and 0.30.1 any newer versions of crystal will not work. 

Download from the https://crystal-lang.org/install/from_targz/

Then create a symbolic link as it wont work if you tell it which crystal to use ie CRYSTAL_BIN=/opt/crystal-0-30-1/bin/crystal

**Comment by ysbaddaden** [comment]
Thanks for reporting! This is now fixed in master.

**Comment by scope2229** [comment]
Thanks @ysbaddaden I'll have a go at trying to dev with crystal so i can help out a little further with updates. Seems the updates weren't too bad. 

I'll give it an install now and see if its worked.
