### ISSUE TITLE
Not loading an app.

### ISSUE THREAD

**Issue by scope2229** [ysbaddaden/prax.cr#93]
I've followed all the setup installed dnsmasq but because of 18.04 i had to follow this answer https://askubuntu.com/a/1041742 otherwise i get a port 53 error. 

after prax start i can goto localhost:20559 & https://localhost:20558 both work fine. 

prax link and firefox myapp.test fails to load the application.

getent hosts circles.dev returns 162.255.119.172 circles.dev 
with .test it returns nothing at all. 

sudo /etc/init.d/prax status
RVM project not found at: /opt/prax
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
2    REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
2    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558
3    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
4    REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558
Chain OUTPUT (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp      ::/0                 ::1                  tcp dpt:80 redir ports 20559
2    REDIRECT   tcp      ::/0                 ::1                  tcp dpt:443 redir ports 20558
Chain PREROUTING (policy ACCEPT)
num  target     prot opt source               destination         
1    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:80 redir ports 20559
2    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:443 redir ports 20558
3    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:80 redir ports 20559
4    REDIRECT   tcp      ::/0                 ::/0                 tcp dpt:443 redir ports 20558

sudo netstat -antup

Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      1249/dnsmasq        
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1048/systemd-resolv 
tcp6       0      0 ::1:53                  :::*                    LISTEN      1249/dnsmasq        
udp        0      0 127.0.0.1:53            0.0.0.0:*                           1249/dnsmasq        
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1048/systemd-resolv 
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1392/dhclient       
udp        0      0 0.0.0.0:631             0.0.0.0:*                           12636/cups-browsed  
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1124/avahi-daemon:  
udp6       0      0 :::40859                :::*                                1124/avahi-daemon:  
udp6       0      0 ::1:53                  :::*                                1249/dnsmasq        
udp6       0      0 :::5353                 :::*                                1124/avahi-daemon:  

I should have left myself with the old ubuntu version instead of the new version

**Comment by ysbaddaden** [comment]
Don't bother with dnsmasq anymore, just use `.localhost`. It should always resolve to `127.0.0.1` and `::1` properly. Note that `.dev` is now a real TLD (owned by Google) so you shouldn't use it anymore, and `.test` needs configuration. I just use `.localhost` nowadays.

I didn't test the port redirection on Bionic, so I can't help much.

**Comment by scope2229** [comment]
Ok i figured it out and everything is working great now. Thanks for your help i might update the manual install page inthe wiki too later 

Basically to use .test domains with rails apps you need to follow a few steps but dnsmasq is not needed at all 

edit /etc/hosts with the following 

127.0.0.1 localhost
127.0.1.1 HOSTNAME
# This is the important bit 
127.0.0.1 *.*.test
# * is a wild card trust me add 2 one for www/api/SUBDOMAIN and another * for your application name eg www.myapp.test or api.myapp.test or admin.myapp.test 

FInally inside application.rb add all your hosts eg. 

config.hosts << "www.myapp.test api.myapp.test admin.myapp.test"

I've tested this on 18.04 18.10 19.04

**Comment by ysbaddaden** [comment]
Sure, dnsmasq just makes it easy to always respond to `*.test` requests with `127.0.0.1` and `::1` so you don't have to configure it manually (hence why I use `.localhost` myself), but that can be achieved manually, yes.
